# Lab and Homework 1: Introduction to Algorithms

**In class**: *Thursday, February 6, 2020*  
**Homework Due** : *5 PM, Thursday, February 13, 2020*

# Learning Goals

Data Engineering is the hardware and software infrastructure for doing Data Science at scale. Netflix processes over one trillion events a day. Their data warehouse is about 100 *petabytes*. Amazon's product database has in exccess of 600 million items. We'll study many of the technologies that underpin data engineering--databases, stream processing, map reduce, etc. To do this, we'll need an intuitive understanding of scale and a conceptual framework for how scale impacts our ability to process massive amounts of data. 

What makes for a "good" program or algorithm? What metrics does one use to assess an algorithm? 

These are the questions we'll explore in this lab. Many of the topics we'll cover in this course (e.g., database indexing) require a conceptual framework and associated terminology to properly grasp. The ideas we develop here will help you underst

As with all the subjects we'll study, we won't begin to scratch the surface of this subject. For further illucidation, Tim Roughgarden's three volume series [_Algorithms Illuminated_](https://www.amazon.com/Algorithms-Illuminated-Part-1-Basics/dp/0999282905/ref=tmm_pap_swatch_0?_encoding=UTF8&qid=1580852108&sr=8-1-spons) is highly recommended. Get the first volume, put it on your nightstand, read a handful of pages before bedtime. You'll be richly rewarded by the end of the semester.

This lab is intended for the three quarters of the students who have not studied Computer Science formally. Those who did will be bored to tears. Feel free to skim.

# Teaching Approach

We roughly follow Aristotle's method of teaching in this course. Instead of explaining principles first and then testing your understanding with problems, we'll often start with a series of leading questions. By grappling with these questions you will intuit and induce the concepts being taught. Questions first, principles, terminology and notation later.


# Searching

## Problem 1: Searching an array
Consider the following Python array. 

In [162]:
a = [3, 1, 5, 2, 4, 9, 8, 7, 6, 10]

Write a function `search_array`, which takes a Python list (aka array) two arguments a list `lst` to search and a value `v` to find. `search_array` returns the index of the element if the element exists in the array and `-1` if the element cannot be found. 

Don't be clever! Implement the first and most obvious thing that comes to mind.

Here's a template for the function:

In [163]:
def search_array(lst, v):
    index = -1
    if v in lst:
        index = lst.index(v)
    return index

In [164]:
search_array(a,2)

3

In [165]:
search_array(a,0)

-1

## Unit Test for Linear Search

In [166]:
import unittest

class TestArraySearch(unittest.TestCase):

    def test_found(self):
        self.assertEqual(search_array(a, 2), 3)
        
    def test_not_found(self):
        self.assertEqual(search_array(a, 11), -1)

# Run the unit tests          
unittest.main(defaultTest="TestArraySearch", argv=['ignored', '-v'], exit=False)
        

test_found (__main__.TestArraySearch) ... ok
test_not_found (__main__.TestArraySearch) ... ok

----------------------------------------------------------------------
Ran 2 tests in 0.017s

OK



The program you just wrote was probably ($P > 0.99$!) _linear_ or _sequential_ search. You scanned the list until you found the first occurence of the search term, or, having reached the end returned `-1`.

Linear search is a perfectly good algorithm. It's simple, it gets the job done. In many cases, it's exactly what you want. For searching a web page or a deck of cards it will do nicely.

But what if you looking for one of the 600 million products on Amazon's store. Would your design suffice? Let's examine that question with three more:

## Problem 2: Analyzing the Search Function

1. What's the **best** case scenario for linear search?
2. What is the **worst** case?
3. What is the **average** case?

The answers to the first two questions are obvious, the last one less so. Here's how to think about it.

Assume that it's equally probable that the search term is located at any of the $n$ array slots. So the search term is _uniformly_ distributed with the probability of it being found at any particular index being $1/n$. You want to compute the _Expected_ value $E$ of the random variable $X$ where $X$ can take on values $0..n-1$ with respective probabilities $p(0), p(1), ... p(n-1) = 1/n$:

$$
E[X] = \sum_{j=1}^N p(j) j
$$

Expand the above expression into a closed form to compute $E[X]$. Hint: look for the arithmetic series.

With the above analysis in hand, would you recommend linear search for Amazon's product database? Assuming it takes $100$ microseconds to iterate over each array element, how long would it take on average to search Amazon's 600 million product records? (We're grossly simplifying by ignoring memory load times and other important details.)







## Problem 3:

Can we improve upon linear search? Sure, if we can make assumptions about the data. For example, the data might already be **sorted**. To see how a sorted list might help, consider the following questions:

1. What is the _median_ element of a sorted list or array? (Think about the definition of medan: the value that separates the lower half of values in the list from the upper half.)
2. How does knowing the median element help narrow the search space and by how much?
3. Having narrowed the space by using the median, could you do it again _recursively_.

In answering the above questions it might help to work with a real list like this one:

In [167]:
sorted_array = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]

# How would you find the element 14 using the approach hinted at above?

Armed with answers to the above questions, write a function called `binary_search` which will do the same thing as the linear `search_array` function you wrote above, except it will take an already sorted array as an argument, compare the search term with the median, and recurse down the left or right sides of the array depending on whether the search term is less than or greater than the median.

In [169]:
import math

def binary_search(a, term, length):
    """
    Search a sorted array.
    
    Parameters:
    a (array): Array to search
    term: What to search for
    length (int): Size of the list
    
    Returns:
    int: index of term if found, -1 otherwise
    """
    left = 0
    right = length - 1
    found = -1
    
    while left <= right:#compare indices
        med = math.floor((left+right)/2)
        if term == a[med]:
            return med  
        elif term < a[med]:
            right = med-1
        else:
            left = med+1
        #length = right - left +1
    
    return found

''' med = round(statistics.median(a))
    candidate = a[med]
    if term == candidate:
        found = med
    else:
        while term != candidate:
            a_prime = a[:round(len(a)/2)]
            if len(a_prime) == len(a):
                break
            binary_search(a_prime,term,len(a))
        
    return found
'''

' med = round(statistics.median(a))\n    candidate = a[med]\n    if term == candidate:\n        found = med\n    else:\n        while term != candidate:\n            a_prime = a[:round(len(a)/2)]\n            if len(a_prime) == len(a):\n                break\n            binary_search(a_prime,term,len(a))\n        \n    return found\n'

In [170]:
a= range(10)
b = 20
c = len(a)

binary_search(a,b,c)

-1

In [171]:
import numpy as np
import unittest

class TestBinarySearch(unittest.TestCase):

    def test_found(self):
        a = np.sort(np.append(np.random.randint(0, 100, 10), 73))
        print(a)
        i = binary_search(a, 73, len(a))
        self.assertEqual(a[i], 73)
        
    def test_not_found(self):
        a = np.sort(np.random.randint(0, 100, 10))
        print(a)
        self.assertEqual(binary_search(a, 101, len(a)), -1)

# Run the unit tests          
unittest.main(defaultTest="TestBinarySearch", argv=['ignored', '-v'], exit=False)

test_found (__main__.TestBinarySearch) ... ok
test_not_found (__main__.TestBinarySearch) ... 

[13 22 29 37 67 73 84 92 92 93 94]
[ 8 12 41 44 65 68 85 90 91 93]


ok

----------------------------------------------------------------------
Ran 2 tests in 0.085s

OK


## Problem: Analyzing Binary Search

What are the best case, worst case, and average case running times for `binary_search` as a function of the length of the input array?

Assuming all of Amazon's 600 million product IDs could be loaded into a sorted array (they are not ever in practice), who many steps on average and at worst, would it take to find a product?

We have just uncovered a class of algorithm called _Divide-and-Conquer_, a fundamental algorithmic technique that has many applications, including to sorting, our next subject.

# Sorting

So `binary_search` dramatically improves over `linear_search`. But how expensive is it to sort? This is the subject we explore now. It turns out that there are fundamental limits to sorting. That is, no algorithm can be devised to exceed the theoretic bound. (We will derive the bound in this course; see an Algorithms book for details.)

In what follows, we'll develop two sorting algorithms: the first a simple and obvious approach called `selection_sort`, the second, called `merge_sort` applies the divide-and-conquer strategy to sorting. 

## Problem: Selection Sort

Selection Sort and it's sibling Insertion Sort are obvious sorting algorithms. You have depended on one or the other whenever you sort a hand of playing cards. 

In both approaches, you split the hand into two parts: sorted and unsorted.

With selection sort you stort by finding the minimum in your unsorted hand. Place that card on the left and keep the unsorted cards to the right. Now scan the unsorted side for the next minimum and move the card to the end of the sorted side. 

When you implement `selection_sort` on a computer you don't maintain two separate arrays for sorted and unsorted. Instead, you sort the array _in place_. 





In [186]:
# Implement Selection Sort

def selection_sort(a):
    myList = list(a)
    for i in range(len(a)):
        small = min(myList[i:]) #O(nlog(n))
        myList.remove(small)
        myList.insert(i,small)
    return myList    

In [187]:
import numpy as np
import unittest

class TestSelectionSort(unittest.TestCase):

    def test_selection_sort(self):
        a = np.random.randint(0, 100, 10)
        print(a)
        #selection_sort(a)
        a = selection_sort(a) #correction to unit test
        b = np.sort(np.array(a, copy=True))
        self.assertSequenceEqual(list(a), list(b))
        print(a)
        

# Run the unit tests          
unittest.main(defaultTest="TestSelectionSort", argv=['ignored', '-v'], exit=False)        


test_selection_sort (__main__.TestSelectionSort) ... 

[61  5 88 81 45 91 54 47 76 33]
[5, 33, 45, 47, 54, 61, 76, 81, 88, 91]


ok

----------------------------------------------------------------------
Ran 1 test in 0.009s

OK


## Problem: Analyzing Selection Sort

Analyze your implementation and give the best, worst and average running times for `selection_sort`.

## Merge Sort

Merge Sort is a Divide and Conquer algorithm invented by John von Neumann in 1945. Like `binary_search` above it splits the input array down the middle. It then recursively calls itself (`merge_sort`) on the left and right halves before merging the now sorted halves into a single sorted result. We will go over the operation of `merge_sort` in detail in class.

The code below shows the recursive top level implementation of `merge_sort`. For homework you should complete the implementation of `merge`, which takes two sorted arrays and merges them into a single sorted array.

In [1]:
def merge_sort(array,*args):
    if len(array)<2:
        return array

    m = len(array)//2
    return merge(merge_sort(array[:m]), merge_sort(array[m:]))
    
def merge(a, b):
    if len(a)* len(b)==0:
        return a+b
    small = list(a[0] < b[0] and a or b).pop(0)
    return [small] + merge(a, b)



### Unit Test for Merge Sort

In [2]:
import numpy as np
import unittest

class TestMergeSort(unittest.TestCase):

    def test_merge_sort(self):
        a = np.random.randint(0, 100, 10)
        print(a)
        merge_sort(a, 0, len(a) - 1)
        b = np.sort(np.array(a, copy=True))
        self.assertSequenceEqual(list(a), list(b))
        print(a)
        

# Run the unit tests          
unittest.main(defaultTest="TestMergeSort", argv=['ignored', '-v'], exit=False)        


test_merge_sort (__main__.TestMergeSort) ... 

[33 41 15 97 40  6 40 82 47 49]


ERROR

ERROR: test_merge_sort (__main__.TestMergeSort)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<ipython-input-2-653d72c8e984>", line 9, in test_merge_sort
    merge_sort(a, 0, len(a) - 1)
  File "<ipython-input-1-8b4de94f2466>", line 6, in merge_sort
    return merge(merge_sort(array[:m]), merge_sort(array[m:]))
  File "<ipython-input-1-8b4de94f2466>", line 6, in merge_sort
    return merge(merge_sort(array[:m]), merge_sort(array[m:]))
  File "<ipython-input-1-8b4de94f2466>", line 6, in merge_sort
    return merge(merge_sort(array[:m]), merge_sort(array[m:]))
  File "<ipython-input-1-8b4de94f2466>", line 12, in merge
    return [small] + merge(a, b)
  File "<ipython-input-1-8b4de94f2466>", line 12, in merge
    return [small] + merge(a, b)
  File "<ipython-input-1-8b4de94f2466>", line 12, in merge
    return [small] + merge(a, b)
  [Previous line repeated 2941 more times]
  File "<ipython-input-1-8b4de94f2466>", 

In [462]:
def merge(a, b):
	if len(a)*len(b) == 0:
		return a+b

	v = (a[0] < b[0] and a or b).pop(0)
	return [v] + merge(a, b)

def mergesort(lst):
	if len(lst) < 2:
		return lst

	m = len(lst)//2
	return merge(mergesort(lst[:m]), mergesort(lst[m:]))

mlst = list(np.random.randint(0, 100, 10))
print (mlst)
sorted = mergesort(mlst)

print (sorted)

[27, 72, 68, 41, 13, 10, 41, 6, 32, 24]
[6, 10, 13, 24, 27, 32, 41, 41, 68, 72]
